version: 2.1

jobs:
  build:
    docker:
      -image: openjdk:8
    steps:
      - checkout
      - run:
          name: clean build
          command: ./mvnw clean install
workflows:
  build-workflow:
    jobs:
      - build
