---
jobs:
  build:
    docker:
      ? "-image"
        : "circleci/openjdk:8-jdk-stretch"
    steps:
      - checkout
      -
        run:
          command: "./mvnw clean install"
          name: "clean build"
version: 2.1
workflows:
  build-workflow:
    jobs:
      - build
