version: '3'

services:

  myapp-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=orderly
      - MYSQL_PASSWORD=root
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql
      - ../src/main/resources/db/init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
  myapp-main:
    image: fthictn/orderly-image
    restart: on-failure
    depends_on:
      - myapp-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=myapp-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=orderly
      - DATABASE_PORT=3307
volumes:
  db_data: